// Package store provides swappable backends that can store secrets generated by
// the encryptor package.
//
// Where suitable, secret stores should return error codes defined in this
// package.
//
// Stores must use whatever encoding scheme is required to safely store binary
// data in the backend - i.e. Base64 if the backend only supports text, gobs if
// it supports binary, etc.
package store
